# Used to test the full app.
# The key difference between prod setup is .env files and Dockerfiles used
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: wheelpicker-backend-test
    env_file:
      - ./backend/.env.test.docker
    ports:
      - "8081:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17.5
    restart: always
    container_name: wheelpicker-database-test
    env_file:
      - ./backend/.env.test.docker
    ports:
      - "5433:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  test_db_data:
