# Used to deploy the app.
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wheelpicker-backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17.5
    restart: always
    container_name: wheelpicker-database
    env_file:
      - ./backend/.env.prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - prod_db_data:/var/lib/postgresql/data

volumes:
  prod_db_data:
