# Used to deploy the app.
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wheelpicker-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17.5
    restart: always
    container_name: wheelpicker-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$${POSTGRES_PASSWORD} psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1;' "]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - prod_db_data:/var/lib/postgresql/data

volumes:
  prod_db_data:
