spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  error:
    whitelabel:
      enabled: false

# Must be BASE64 format
jwtUtility:
  accessSecretKey: VGhlIGRlZmF1bHQgdW5zZWN1cmUgc3RyaW5nIHVzZWQgZm9yIC5lbnYgY29uZmlnIGFzIEpXVF9BQ0NFU1NfU0VDUkVUX0tFWQ==
  # 15 min
  accessTokenExpiryMs: 900000

  refreshSecretKey: VGhlIGRlZmF1bHQgdW5zZWN1cmUgc3RyaW5nIHVzZWQgZm9yIC5lbnYgY29uZmlnIGFzIEpXVF9SRUZSRVNIX1NFQ1JFVF9LRVk=
  # 1 hour
  refreshTokenExpiryMs: 3600000