spring:
  config:
    import: classpath:application-prod-secrets.yml
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  error:
    whitelabel:
      enabled: false

jwtUtility:
  accessSecretKey: ${JWT_ACCESS_SECRET_KEY}
  accessTokenExpiryMs: ${JWT_ACCESS_SECRET_EXPIRY_MS}
  refreshSecretKey: ${JWT_REFRESH_SECRET_KEY}
  refreshTokenExpiryMs: ${JWT_REFRESH_SECRET_EXPIRY_MS}

logging:
  level:
    root: WARN