name: Test App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Load backend environment variables
        run: export $(cat backend/.env.test | grep -v '^#' | xargs)
        shell: bash

      - name: Run Tests
        run: |
          cd backend
          mvn clean test